# Generated by Django 6.1.1 on 2026-09-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('season', models.PositiveSmallIntegerField(help_text='e.g. 2026', verbose_name='season')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('regulation', models.TextField(blank=True, help_text='Full text of the competition rules.', verbose_name='regulation')),
                ('regulation_file', models.FileField(blank=True, help_text='Official rules document (PDF).', upload_to='championships/regulations/', verbose_name='regulation file')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration open'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('points_per_win', models.PositiveSmallIntegerField(default=3, verbose_name='points per win')),
                ('points_per_draw', models.PositiveSmallIntegerField(default=1, verbose_name='points per draw')),
                ('points_per_loss', models.PositiveSmallIntegerField(default=0, verbose_name='points per loss')),
                ('yellow_cards_for_suspension', models.PositiveSmallIntegerField(default=3, verbose_name='yellow cards for suspension')),
                ('max_players_per_team', models.PositiveSmallIntegerField(default=25, verbose_name='max players per team')),
            ],
            options={
                'verbose_name': 'championship',
                'verbose_name_plural': 'championships',
                'ordering': ('-season', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ChampionshipTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('group', models.CharField(blank=True, help_text="Group label, e.g. 'A'.", max_length=10, verbose_name='group')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='withdrawn')),
                ('played', models.PositiveSmallIntegerField(default=0, verbose_name='played')),
                ('wins', models.PositiveSmallIntegerField(default=0, verbose_name='wins')),
                ('draws', models.PositiveSmallIntegerField(default=0, verbose_name='draws')),
                ('losses', models.PositiveSmallIntegerField(default=0, verbose_name='losses')),
                ('goals_for', models.PositiveSmallIntegerField(default=0, verbose_name='goals for')),
                ('goals_against', models.PositiveSmallIntegerField(default=0, verbose_name='goals against')),
                ('points', models.SmallIntegerField(default=0, help_text='May go negative after point deductions.', verbose_name='points')),
                ('points_deducted', models.PositiveSmallIntegerField(default=0, verbose_name='points deducted')),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0, verbose_name='yellow cards')),
                ('red_cards', models.PositiveSmallIntegerField(default=0, verbose_name='red cards')),
                ('rank', models.PositiveSmallIntegerField(blank=True, help_text='Final position within the group after tie-breakers.', null=True, verbose_name='rank')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_entries', to='championships.championship', verbose_name='championship')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='championship_entries', to='teams.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'championship team',
                'verbose_name_plural': 'championship teams',
                'ordering': ('championship', 'group', 'rank', 'team__name'),
            },
        ),
        migrations.AddField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(related_name='championships', through='championships.ChampionshipTeam', to='teams.team', verbose_name='teams'),
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='shirt number')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RELEASED', 'Released')], db_index=True, default='ACTIVE', max_length=20, verbose_name='status')),
                ('registered_on', models.DateField(verbose_name='registered on')),
                ('released_on', models.DateField(blank=True, null=True, verbose_name='released on')),
                ('championship_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='championships.championshipteam', verbose_name='championship team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='teams.player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'player registration',
                'verbose_name_plural': 'player registrations',
                'ordering': ('championship_team', 'shirt_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='championshipteam',
            constraint=models.UniqueConstraint(fields=('championship', 'team'), name='unique_team_per_championship'),
        ),
        migrations.AddConstraint(
            model_name='championship',
            constraint=models.UniqueConstraint(fields=('name', 'season'), name='unique_championship_per_season'),
        ),
        migrations.AddConstraint(
            model_name='championship',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='championship_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='playerregistration',
            constraint=models.UniqueConstraint(fields=('championship_team', 'player'), name='unique_player_per_championship_team'),
        ),
        migrations.AddConstraint(
            model_name='playerregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'RELEASED'), _negated=True), fields=('championship_team', 'shirt_number'), name='unique_active_shirt_number_per_team'),
        ),
        migrations.AddConstraint(
            model_name='playerregistration',
            constraint=models.CheckConstraint(condition=models.Q(('released_on__isnull', True), ('released_on__gte', models.F('registered_on')), _connector='OR'), name='registration_release_after_start'),
        ),
    ]
