# Generated by Django 6.1.1 on 2026-09-30 01:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('state', models.CharField(default='PI', max_length=2, verbose_name='state')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('name', 'state'), name='unique_city_per_state')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('nickname', models.CharField(blank=True, help_text='Name shown in live feeds.', max_length=60, verbose_name='nickname')),
                ('document_number', models.CharField(blank=True, help_text='Official ID (e.g. CPF) used to prevent duplicate registrations.', max_length=20, null=True, unique=True, verbose_name='document number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2, verbose_name='position')),
                ('preferred_foot', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], max_length=1, verbose_name='preferred foot')),
                ('photo', models.ImageField(blank=True, upload_to='players/photos/', verbose_name='photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['full_name'], name='teams_playe_full_na_48b839_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stadiums', to='teams.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'stadium',
                'verbose_name_plural': 'stadiums',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('short_name', models.CharField(help_text='Abbreviation shown on the scoreboard.', max_length=5, verbose_name='short name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('crest', models.ImageField(blank=True, upload_to='teams/crests/', verbose_name='crest')),
                ('primary_color', models.CharField(blank=True, help_text='Hex colour, e.g. #1A2B3C.', max_length=7, verbose_name='primary colour')),
                ('secondary_color', models.CharField(blank=True, max_length=7, verbose_name='secondary colour')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)], verbose_name='founded in')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.city', verbose_name='city')),
                ('home_stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_teams', to='teams.stadium', verbose_name='home stadium')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='stadium',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_stadium_per_city'),
        ),
    ]
