# Generated by Django 6.1.1 on 2026-09-30 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championships', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="e.g. 'goal', 'yellow-card'.", max_length=40, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('category', models.CharField(choices=[('SCORING', 'Scoring'), ('DISCIPLINARY', 'Disciplinary'), ('SUBSTITUTION', 'Substitution'), ('SHOOTOUT', 'Penalty shoot-out'), ('MATCH_FLOW', 'Match flow'), ('OTHER', 'Other')], max_length=20, verbose_name='category')),
                ('score_effect', models.CharField(choices=[('NONE', 'Does not change the score'), ('FOR_TEAM', "Goal for the event's team"), ('FOR_OPPONENT', 'Goal for the opponent (own goal)')], default='NONE', max_length=20, verbose_name='score effect')),
                ('counts_as_yellow_card', models.BooleanField(default=False, verbose_name='counts as yellow card')),
                ('counts_as_red_card', models.BooleanField(default=False, verbose_name='counts as red card')),
                ('requires_team', models.BooleanField(default=True, help_text='False for events such as kick-off or full-time.', verbose_name='requires team')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'event type',
                'verbose_name_plural': 'event types',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('event_types', models.ManyToManyField(blank=True, help_text='Event types in which this role may appear.', related_name='allowed_roles', to='matches.eventtype', verbose_name='event types')),
            ],
            options={
                'verbose_name': 'event role',
                'verbose_name_plural': 'event roles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stage', models.CharField(choices=[('GROUP', 'Group stage'), ('ROUND_OF_16', 'Round of 16'), ('QUARTER_FINAL', 'Quarter-final'), ('SEMI_FINAL', 'Semi-final'), ('THIRD_PLACE', 'Third-place play-off'), ('FINAL', 'Final')], default='GROUP', max_length=20, verbose_name='stage')),
                ('round_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='round')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='scheduled at')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('FIRST_HALF', 'First half'), ('HALF_TIME', 'Half-time'), ('SECOND_HALF', 'Second half'), ('EXTRA_TIME', 'Extra time'), ('PENALTIES', 'Penalty shoot-out'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELED', 'Canceled')], db_index=True, default='SCHEDULED', max_length=20, verbose_name='status')),
                ('referee_name', models.CharField(blank=True, max_length=150, verbose_name='referee')),
                ('streaming_url', models.URLField(blank=True, help_text='Live broadcast link (e.g. YouTube), when available.', verbose_name='streaming link')),
                ('home_score', models.PositiveSmallIntegerField(default=0, verbose_name='home score')),
                ('away_score', models.PositiveSmallIntegerField(default=0, verbose_name='away score')),
                ('home_penalty_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='home penalty score')),
                ('away_penalty_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='away penalty score')),
                ('is_walkover', models.BooleanField(default=False, verbose_name='walkover')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='championships.championshipteam', verbose_name='away team')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='championships.championship', verbose_name='championship')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='championships.championshipteam', verbose_name='home team')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='teams.stadium', verbose_name='stadium')),
                ('table_officials', models.ManyToManyField(blank=True, help_text='Users allowed to record events for this match.', related_name='officiated_matches', to=settings.AUTH_USER_MODEL, verbose_name='table officials')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'ordering': ('scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('STARTER', 'Starter'), ('SUBSTITUTE', 'Substitute')], default='STARTER', max_length=20, verbose_name='role')),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='shirt number')),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2, verbose_name='position')),
                ('is_captain', models.BooleanField(default=False, verbose_name='captain')),
                ('player_registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups', to='championships.playerregistration', verbose_name='player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups', to='championships.championshipteam', verbose_name='team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'lineup entry',
                'verbose_name_plural': 'lineup entries',
                'ordering': ('match', 'team', 'role', 'shirt_number'),
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'First half'), (2, 'Second half'), (3, 'Extra time - first half'), (4, 'Extra time - second half'), (5, 'Penalty shoot-out')], verbose_name='period')),
                ('minute', models.PositiveSmallIntegerField(help_text='Regular-time minute, e.g. 45.', verbose_name='minute')),
                ('stoppage_minute', models.PositiveSmallIntegerField(default=0, help_text='Added time, e.g. 2 for 45+2.', verbose_name='stoppage time')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='canceled')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='canceled at')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_events', to=settings.AUTH_USER_MODEL, verbose_name='canceled by')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='matches.eventtype', verbose_name='event type')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match', verbose_name='match')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_events', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_events', to='championships.championshipteam', verbose_name='team')),
            ],
            options={
                'verbose_name': 'match event',
                'verbose_name_plural': 'match events',
                'ordering': ('match', 'period', 'minute', 'stoppage_minute', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='MatchEventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.matchevent', verbose_name='event')),
                ('player_registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to='championships.playerregistration', verbose_name='player')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='matches.eventrole', verbose_name='role')),
            ],
            options={
                'verbose_name': 'event participant',
                'verbose_name_plural': 'event participants',
            },
        ),
        migrations.AddField(
            model_name='matchevent',
            name='players',
            field=models.ManyToManyField(related_name='match_events', through='matches.MatchEventParticipant', to='championships.playerregistration', verbose_name='players'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['championship', 'status'], name='matches_mat_champio_65d3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['championship', 'round_number'], name='matches_mat_champio_bf283d_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='match_teams_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='lineup',
            constraint=models.UniqueConstraint(fields=('match', 'player_registration'), name='unique_player_per_match_lineup'),
        ),
        migrations.AddConstraint(
            model_name='lineup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_captain', True)), fields=('match', 'team'), name='one_captain_per_team_per_match'),
        ),
        migrations.AddConstraint(
            model_name='matcheventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'player_registration', 'role'), name='unique_participant_role_per_event'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'is_canceled'], name='matches_mat_match_i_c63466_idx'),
        ),
    ]
